version: '3.5'

services:
  app:
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "7777:80"
    volumes:
      - "./data:/data/"
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
      - flame.type=application
      - flame.name=Vaultwarden
      - flame.url=${SITE_URL}
      - flame.category=Productivity
      - flame.icon=onepassword
    networks:
      - productivity_vaultwarden

networks:
  productivity_vaultwarden:
    name: productivity_vaultwarden
    driver: bridge